// =====================================================================
// MONSTER_DATA — refactored to support tactical RPG mechanics.
//
// Move shape (conceptual interface):
//   {
//     name: string,                       // canavar yeteneğinin adı
//     type: 'damage' | 'heal' | 'buff' | 'debuff' |
//           'stun'   | 'lifesteal' | 'recoil' | 'dot',
//     basePower?: number,                 // ham hasar/iyileşme tabanı
//     accuracy?: number,                  // 0-100 isabet (varsayılan 100)
//     target: 'self' | 'enemy',
//     effect?: {
//       stat?: 'hp' | 'power' | 'defense' | 'accuracy' | 'speed',
//       modifier?: number,                // buff için 1.5, debuff için 0.5 vb.
//                                         //    DoT için tur başı hasar (sayı)
//       duration?: number,                // efektin kaç tur süreceği
//       chance?: number                   // 0-1 arası tetiklenme ihtimali
//     },
//     description: string
//   }
//
// Geriye dönük uyumluluk: buildMonsterCatalog hâlâ eski
// { attack, damage } formatını da kabul ediyor (otomatik damage'a çevrilir).
// =====================================================================

window.MONSTER_DATA = [
  {
    id: "libcub",
    name: "Libcub",
    project: "libft",
    milestone: 0,
    role: "Tank starter",
    color: "#45c7ff",
    hp: 120, power: 2, defense: 13, speed: 2,
    moves: [
      { name: "Null Guard", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.5, duration: 3 },
        description: "NULL kontrolü sıkılaştırır — 3 tur boyunca defansı %50 artar." },
      { name: "Memory Allocation", type: "heal", basePower: 35, accuracy: 100, target: "self",
        description: "Taze malloc ile kendine 35 HP iyileşir." },
      { name: "Bzero Blast", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 0.7, duration: 3, chance: 1.0 },
        description: "Hafıza sıfırlar — hasar verir ve düşmanın gücünü %30 düşürür." },
      { name: "Calloc Catalyst", type: "damage", basePower: 26, accuracy: 90, target: "enemy",
        description: "Temizlenmiş bellek dalgasıyla güçlü darbe." },
      { name: "Length Lash", type: "damage", basePower: 16, accuracy: 100, target: "enemy",
        description: "Strlen tabanlı hızlı, isabetli vuruş." }
    ]
  },
  {
    id: "printfox",
    name: "Printfox",
    project: "ft_printf",
    milestone: 1,
    role: "Format mage",
    color: "#ffbd4a",
    hp: 90, power: 5, defense: 9, speed: 4,
    moves: [
      { name: "Format Flame", type: "damage", basePower: 28, accuracy: 90, target: "enemy",
        description: "%s alev kusar — yüksek hasar." },
      { name: "Variadic Void", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Düzgün biçimsiz format — düşmanın isabetini %25 düşürür." },
      { name: "Hexadecimal Haze", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 8, duration: 3 },
        description: "0x hex sis — 3 tur boyunca tur başı 8 hasar." },
      { name: "Pointer Pierce", type: "damage", basePower: 32, accuracy: 80, target: "enemy",
        description: "%p ile zırh deler ama az isabetli." },
      { name: "Character Chop", type: "damage", basePower: 16, accuracy: 100, target: "enemy",
        description: "%c ile hızlı, isabetli darbe." }
    ]
  },
  {
    id: "linewyrm",
    name: "Linewyrm",
    project: "get_next_line",
    milestone: 1,
    role: "Buffer serpent",
    color: "#78d66f",
    hp: 112, power: 3, defense: 11, speed: 4,
    moves: [
      { name: "Buffer Bite", type: "lifesteal", basePower: 22, accuracy: 95, target: "enemy",
        description: "Buffer ısırığı — hasarın %50'sini can olarak çalar." },
      { name: "Newline Strike", type: "damage", basePower: 24, accuracy: 95, target: "enemy",
        description: "\\n tetikli keskin vuruş." },
      { name: "Static Shield", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.4, duration: 3 },
        description: "Static değişken kalkanı — 3 tur defans %40 artar." },
      { name: "EOF Evade", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "accuracy", modifier: 1.3, duration: 4 },
        description: "EOF kaçışı — 4 tur isabet %30 artar." },
      { name: "Free Fangs", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Boşa çıkarılmış bellekle ısırır, düşman gücünü %20 düşürür." }
    ]
  },
  {
    id: "stackdrake",
    name: "Stackdrake",
    project: "push_swap",
    milestone: 1,
    role: "Stack assassin",
    color: "#ff5e57",
    hp: 104, power: 5, defense: 10, speed: 5,
    moves: [
      { name: "Swap Strike", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.7, duration: 3, chance: 1.0 },
        description: "Swap darbesi — hasar verir, düşman defansını %30 düşürür." },
      { name: "Push Pounce", type: "damage", basePower: 22, accuracy: 95, target: "enemy",
        description: "Stack üstüne sıçrayarak vurur." },
      { name: "Double Rotate", type: "damage", basePower: 38, accuracy: 85, target: "enemy",
        description: "rr/rrr kombinasyonu — iki yığını birden döndürerek devasa hasar." },
      { name: "Reverse Rage", type: "damage", basePower: 26, accuracy: 90, target: "enemy",
        effect: { stat: "power", modifier: 1.2, duration: 2, chance: 1.0 },
        description: "Ters rotasyon — hasar verir ve 2 tur kendi gücünü %20 artırır.", buffSelf: true },
      { name: "Pivot Point", type: "damage", basePower: 28, accuracy: 85, target: "enemy",
        description: "Medyan pivota göre kesin darbe." }
    ]
  },
  {
    id: "golemroot",
    name: "Golemroot",
    project: "Born2beroot",
    spriteFile: "Born2beroot.png",
    milestone: 2,
    role: "System tank",
    color: "#8fa3ad",
    hp: 140, power: 2, defense: 14, speed: 2,
    moves: [
      { name: "Sudo Shield", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 2.0, duration: 3 },
        description: "sudo elevasyonu — 3 tur boyunca defansı 2 katına çıkar." },
      { name: "Password Purge", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Parola politikasıyla düşmanın isabetini %25 düşürür." },
      { name: "Port Protect", type: "heal", basePower: 28, accuracy: 100, target: "self",
        description: "UFW kuralı uygular — kendine 28 HP iyileşir." },
      { name: "Firewall Fort", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.5, duration: 2 },
        description: "Kalıcı duvar — 2 tur defans %50 artar." },
      { name: "Cron Crush", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 14, duration: 3 },
        description: "cron job kurar — 3 tur boyunca tur başı 14 hasar." }
    ]
  },
  {
    id: "mazewalker",
    name: "Mazewalker",
    project: "A-Maze-ing",
    spriteFile: "A-Maze-ing.png",
    milestone: 2,
    role: "Maze scout",
    color: "#b683ff",
    hp: 92, power: 4, defense: 10, speed: 5,
    moves: [
      { name: "Flood Fill", type: "damage", basePower: 24, accuracy: 90, target: "enemy",
        description: "Tüm odaları su basar — geniş alan hasarı." },
      { name: "Shortest Slash", type: "damage", basePower: 28, accuracy: 90, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "En kısa yol — hasar verip kendi hızını %30 artırır.", buffSelf: true },
      { name: "Backtrack Bite", type: "lifesteal", basePower: 18, accuracy: 95, target: "enemy",
        description: "Geri izi sürerek can çalar (hasarın %50'si)." },
      { name: "Deadend Detonation", type: "damage", basePower: 32, accuracy: 80, target: "enemy",
        description: "Çıkmaz noktasında patlatır — yüksek hasar." },
      { name: "Matrix Mauling", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Labirent matrisini parçalar, düşman defansını %20 düşürür." }
    ]
  },
  {
    id: "pymamba",
    name: "PyMamba",
    project: "Python Module 00-10",
    spriteFile: "Python_Module_00-10.png",
    milestone: 2,
    role: "Data mage",
    color: "#4bd27d",
    hp: 96, power: 5, defense: 9, speed: 4,
    moves: [
      { name: "Comprehension Crush", type: "damage", basePower: 22, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "List comprehension — hasar + düşman gücü %20 düşer." },
      { name: "Decorator Doom", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "power", modifier: 1.4, duration: 3 },
        description: "@decorator sarmalar — 3 tur kendi gücü %40 artar." },
      { name: "NumPy Nova", type: "damage", basePower: 30, accuracy: 85, target: "enemy",
        description: "Vectorize edilmiş yıldız patlaması." },
      { name: "Magic Matrix", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 10, duration: 3 },
        description: "Matris büyüsü — 3 tur tur başı 10 hasar." },
      { name: "Pandas Pounce", type: "damage", basePower: 24, accuracy: 90, target: "enemy",
        description: "DataFrame ağırlığıyla zıplar." }
    ]
  },
  {
    id: "ringmaster",
    name: "Ringmaster",
    project: "Call Me Maybe",
    milestone: 3,
    role: "Async trickster",
    color: "#ff6fb1",
    hp: 88, power: 4, defense: 10, speed: 5,
    moves: [
      { name: "Callback Chaos", type: "stun", accuracy: 70, target: "enemy",
        effect: { duration: 1 },
        description: "Çakışan callback'ler — düşman 1 tur sersemler." },
      { name: "Signal Spike", type: "damage", basePower: 26, accuracy: 90, target: "enemy",
        description: "Async sinyal sivri vuruşu." },
      { name: "Handler Haven", type: "heal", basePower: 25, accuracy: 100, target: "self",
        description: "Error handler — 25 HP iyileşir." },
      { name: "Async Abyss", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "speed", modifier: 0.7, duration: 3, chance: 1.0 },
        description: "Düşmanı bekleyen kuyruğa sokar — hızı %30 düşer." },
      { name: "Function Pointer Pierce", type: "damage", basePower: 28, accuracy: 90, target: "enemy",
        description: "Dolaylı çağrı — keskin nokta hasarı." }
    ]
  },
  {
    id: "hoverdrone",
    name: "Hoverdrone",
    project: "Fly-in",
    milestone: 3,
    role: "Network striker",
    color: "#53d8ff",
    hp: 90, power: 4, defense: 10, speed: 5,
    moves: [
      { name: "Packet Ping", type: "damage", basePower: 16, accuracy: 100, target: "enemy",
        description: "Garantili ICMP darbesi." },
      { name: "Port Proxy", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Proxy redirect — hasar + düşman defansı %20 düşer." },
      { name: "IP Inbound", type: "damage", basePower: 24, accuracy: 90, target: "enemy",
        description: "Gelen istek selini başlatır." },
      { name: "Request Rush", type: "damage", basePower: 28, accuracy: 88, target: "enemy",
        description: "Yoğun istek dalgası." },
      { name: "Timeout Trap", type: "stun", accuracy: 65, target: "enemy",
        effect: { duration: 1 },
        description: "Düşmanı zaman aşımına sokar — 1 tur sersemler." }
    ]
  },
  {
    id: "codexgolem",
    name: "Codexgolem",
    project: "Codexion",
    milestone: 3,
    role: "Refactor bruiser",
    color: "#9dd7ff",
    hp: 116, power: 3, defense: 12, speed: 3,
    moves: [
      { name: "Clean Code Crush", type: "damage", basePower: 22, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 1.3, duration: 3, chance: 1.0 },
        description: "Temiz kod darbesi — hasar verirken kendi defansı %30 artar.", buffSelf: true },
      { name: "Refactor Ray", type: "heal", basePower: 28, accuracy: 100, target: "self",
        description: "Refactor enerjisiyle 28 HP iyileşir." },
      { name: "Modular Matrix", type: "damage", basePower: 30, accuracy: 88, target: "enemy",
        description: "Modüler matris çarpışması." },
      { name: "Comment Cleanse", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "power", modifier: 1.3, duration: 3 },
        description: "Yorum temizliği — 3 tur kendi gücü %30 artar." },
      { name: "Bug Buster", type: "damage", basePower: 24, accuracy: 90, target: "enemy",
        effect: { stat: "power", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Bug ezici — hasar + düşman gücü %20 düşer." }
    ]
  },
  {
    id: "vectorvark",
    name: "Vectorvark",
    project: "RAG against the machine",
    milestone: 4,
    role: "RAG tactician",
    color: "#a78bfa",
    hp: 104, power: 4, defense: 10, speed: 4,
    moves: [
      { name: "Vector Embed", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "accuracy", modifier: 1.3, duration: 3 },
        description: "Embedding alanı — 3 tur isabet %30 artar." },
      { name: "Prompt Power", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        description: "İyi mühendislenmiş prompt darbesi." },
      { name: "Cosine Crush", type: "damage", basePower: 32, accuracy: 82, target: "enemy",
        description: "Cosine benzerliğiyle hedefi kilitler." },
      { name: "Context Cleanse", type: "heal", basePower: 26, accuracy: 100, target: "self",
        description: "Bağlamı temizleyip 26 HP iyileşir." },
      { name: "Anti-Hallucination", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Düşmanın yanılsamalarını söker — isabet %25 düşer." }
    ]
  },
  {
    id: "pacgolem",
    name: "Pacgolem",
    project: "Pac-Man",
    milestone: 4,
    role: "Arcade bruiser",
    color: "#ffd166",
    hp: 112, power: 4, defense: 12, speed: 3,
    moves: [
      { name: "Ghost Chaser", type: "damage", basePower: 24, accuracy: 90, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Hayalet kovalar — hasar + kendi hızı %30 artar.", buffSelf: true },
      { name: "Power Pellet", type: "damage", basePower: 30, accuracy: 88, target: "enemy",
        effect: { stat: "power", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Power pellet — hasar + kendi gücü %30 artar.", buffSelf: true },
      { name: "Grid Glide", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.4, duration: 3 },
        description: "Grid kayışı — 3 tur defans %40 artar." },
      { name: "Pellet Popping", type: "damage", basePower: 18, accuracy: 100, target: "enemy",
        description: "Garantili nokta yiyişi." },
      { name: "Fruit Frenzy", type: "heal", basePower: 22, accuracy: 100, target: "self",
        description: "Bonus meyve — 22 HP iyileşir." }
    ]
  },
  {
    id: "netspider",
    name: "Netspider",
    project: "NetPractice",
    milestone: 4,
    role: "Network controller",
    color: "#56cfe1",
    hp: 106, power: 3, defense: 11, speed: 4,
    moves: [
      { name: "Subnet Slash", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        description: "CIDR kesimi." },
      { name: "Gateway Grip", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "speed", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Gateway tıkanması — düşman hızı %25 düşer." },
      { name: "Broadcast Blast", type: "damage", basePower: 28, accuracy: 85, target: "enemy",
        description: "Broadcast adresine yayın saldırısı." },
      { name: "IP Conflict", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 10, duration: 3 },
        description: "IP çakışması — 3 tur tur başı 10 hasar." },
      { name: "Router Rush", type: "stun", accuracy: 60, target: "enemy",
        effect: { duration: 1 },
        description: "Yönlendirme tablosu çöker — 1 tur sersemleme." }
    ]
  },
  {
    id: "agent-smith",
    name: "Agent Smith",
    project: "Agent Smith",
    milestone: 5,
    role: "Cyber assassin",
    color: "#6c757d",
    hp: 94, power: 5, defense: 9, speed: 5,
    moves: [
      { name: "Nmap Needle", type: "damage", basePower: 22, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.7, duration: 3, chance: 1.0 },
        description: "Port taraması — hasar + düşman defansı %30 düşer." },
      { name: "Metasploit Maverick", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 14, duration: 3 },
        description: "Virüs payload — 3 tur boyunca tur başı 14 hasar." },
      { name: "Payload Pounce", type: "damage", basePower: 28, accuracy: 88, target: "enemy",
        description: "Payload teslimatı — yüksek hasar." },
      { name: "Reverse Shell Rush", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 0.6, duration: 3, chance: 1.0 },
        description: "Bind shell ele geçirir — düşman gücü %40 düşer." },
      { name: "Bruteforce Blast", type: "damage", basePower: 36, accuracy: 75, target: "enemy",
        description: "Brute force — az isabetli ama yıkıcı." }
    ]
  },
  {
    id: "protocol-x",
    name: "Protocol-X",
    project: "The Answer Protocol",
    spriteFile: "The_Answer_Protocol.png",
    milestone: 5,
    role: "Protocol striker",
    color: "#f77f00",
    hp: 100, power: 4, defense: 10, speed: 4,
    moves: [
      { name: "Status Strike (200 OK)", type: "damage", basePower: 24, accuracy: 95, target: "enemy",
        description: "Onaylı çağrı — temiz hasar." },
      { name: "NotFound Nova (404)", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "404 patlaması — hasar + düşman isabeti %20 düşer." },
      { name: "Handshake Hook", type: "damage", basePower: 28, accuracy: 88, target: "enemy",
        description: "3-way handshake çengeli." },
      { name: "Server Error Slam (500)", type: "recoil", basePower: 38, accuracy: 85, target: "enemy",
        description: "500 ile yıkıcı çarpma — hasarın %25'i geri teper." },
      { name: "Header Heave", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 1.2, duration: 2, chance: 1.0 },
        description: "Header üst üste binmesi — hasar + kendi gücü %20 artar.", buffSelf: true }
    ]
  },
  {
    id: "inceptionizer",
    name: "Inceptionizer",
    project: "Inception",
    milestone: 5,
    role: "Container tank",
    color: "#80ed99",
    hp: 132, power: 3, defense: 14, speed: 3,
    moves: [
      { name: "Container Compose", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.6, duration: 3 },
        description: "Docker compose zırhı — 3 tur defans %60 artar." },
      { name: "Volume Vault", type: "heal", basePower: 32, accuracy: 100, target: "self",
        description: "Persistent volume — 32 HP iyileşir." },
      { name: "Network Nexus", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "speed", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Bridge network — hasar + düşman hızı %25 düşer." },
      { name: "Daemon Detonation", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 12, duration: 3 },
        description: "Arka plan daemon — 3 tur tur başı 12 hasar." },
      { name: "Image Influx", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 1.2, duration: 2, chance: 1.0 },
        description: "Image katmanları — hasar + kendi gücü %20 artar.", buffSelf: true }
    ]
  },
  {
    id: "resumancer",
    name: "Resumancer",
    project: "42_Collaborative_resume",
    milestone: 6,
    role: "Support debuffer",
    color: "#cdb4db",
    hp: 108, power: 2, defense: 11, speed: 3,
    moves: [
      { name: "Collaborative Commit", type: "damage", basePower: 16, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 0.6, duration: 3, chance: 1.0 },
        description: "Birlikte commit — düşman gücü %40 düşer." },
      { name: "Markdown Mastery", type: "damage", basePower: 14, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.6, duration: 3, chance: 1.0 },
        description: "Markdown vuruşu — düşman defansı %40 düşer." },
      { name: "Conflict Resolution", type: "heal", basePower: 28, accuracy: 100, target: "self",
        description: "Merge conflict çözümü — 28 HP iyileşir." },
      { name: "Pull Request Power", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "PR review — hasar + düşman isabeti %25 düşer." },
      { name: "Repo Rush", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.4, duration: 3 },
        description: "Repo siperi — 3 tur defans %40 artar." }
    ]
  },
  {
    id: "neonpong",
    name: "Neonpong",
    project: "ft_transcendence",
    milestone: 6,
    role: "Real-time striker",
    color: "#00f5d4",
    hp: 90, power: 5, defense: 9, speed: 6,
    moves: [
      { name: "WebSocket Wave", type: "damage", basePower: 30, accuracy: 90, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Real-time dalga — hasar + kendi hızı %30 artar.", buffSelf: true },
      { name: "Single Page Smash", type: "damage", basePower: 26, accuracy: 90, target: "enemy",
        description: "SPA çarpışması — yüksek hasar." },
      { name: "JWT Jacket", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.3, duration: 2 },
        description: "JWT zırhı — 2 tur defans %30 artar." },
      { name: "Auth Armor (2FA)", type: "heal", basePower: 20, accuracy: 100, target: "self",
        description: "İki faktörlü onarım — 20 HP iyileşir." },
      { name: "Database Duel", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "speed", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "DB sorgu yarışı — düşman hızı %25 düşer." }
    ]
  },
  {
    id: "libftaur",
    name: "Libftaur",
    project: "Libft",
    milestone: 0,
    track: "legacy",
    role: "Memory bruiser",
    color: "#3bb7ff",
    hp: 118, power: 3, defense: 12, speed: 3,
    moves: [
      { name: "Memset Mangle", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "defense", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "memset taraması — düşman defansı %25 düşer." },
      { name: "Pointer Pounce", type: "damage", basePower: 26, accuracy: 90, target: "enemy",
        description: "Pointer sıçraması — keskin nokta vuruşu." },
      { name: "Malloc Magic", type: "heal", basePower: 30, accuracy: 100, target: "self",
        description: "Yeni blok malloc — 30 HP iyileşir." },
      { name: "Substr Slash", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        description: "Substring dilimi." },
      { name: "Bonus Bond (Linked List)", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.5, duration: 3 },
        description: "Bağlı liste zinciri — 3 tur defans %50 artar." }
    ]
  },
  {
    id: "pipexus",
    name: "Pipexus",
    project: "pipex",
    milestone: 2,
    track: "legacy",
    role: "Process controller",
    color: "#69d2e7",
    hp: 104, power: 3, defense: 11, speed: 4,
    moves: [
      { name: "Fork Frenzy", type: "recoil", basePower: 32, accuracy: 90, target: "enemy",
        description: "Fork bombası — yüksek hasar ama %25'i geri teper." },
      { name: "Pipe Punch", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Pipe geçişi — hasar + kendi hızı %30 artar.", buffSelf: true },
      { name: "Dup2 Duplicate", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.4, duration: 2 },
        description: "dup2 yedeği — 2 tur defans %40 artar." },
      { name: "Execve Execute", type: "damage", basePower: 28, accuracy: 88, target: "enemy",
        description: "execve patlaması — büyük hasar." },
      { name: "Waitpid Watch", type: "heal", basePower: 22, accuracy: 100, target: "self",
        description: "Çocuk süreç bekleyişi — 22 HP iyileşir." }
    ]
  },
  {
    id: "signalsaur",
    name: "Signalsaur",
    project: "minitalk",
    milestone: 2,
    track: "legacy",
    role: "Signal striker",
    color: "#00b4d8",
    hp: 94, power: 3, defense: 9, speed: 5,
    moves: [
      { name: "Signal One (SIGUSR1)", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        description: "USR1 sinyali — temiz hasar." },
      { name: "Signal Two (SIGUSR2)", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "USR2 sinyali — düşman isabeti %20 düşer." },
      { name: "Kill Command", type: "damage", basePower: 75, accuracy: 30, target: "enemy",
        description: "SIGKILL — nadiren isabet eder ama isabet ederse devirir." },
      { name: "Bit Shift Bash", type: "damage", basePower: 26, accuracy: 90, target: "enemy",
        description: "Bit kaydırma darbesi." },
      { name: "Sigaction Shield", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.5, duration: 3 },
        description: "sigaction handler — 3 tur defans %50 artar." }
    ]
  },
  {
    id: "longwalker",
    name: "Longwalker",
    project: "so_long",
    milestone: 2,
    track: "legacy",
    role: "Map guardian",
    color: "#8ac926",
    hp: 110, power: 3, defense: 12, speed: 3,
    moves: [
      { name: "MiniLibX Window", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "defense", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "MiniLibX penceresi — düşman defansı %25 düşer." },
      { name: "Flood Fill Force", type: "damage", basePower: 28, accuracy: 88, target: "enemy",
        description: "Flood fill — büyük alan hasarı." },
      { name: "Key Hook Hack", type: "stun", accuracy: 60, target: "enemy",
        effect: { duration: 1 },
        description: "Tuş yakalama — düşman 1 tur sersemler." },
      { name: "XPM X-ray", type: "heal", basePower: 24, accuracy: 100, target: "self",
        description: "XPM piksel onarımı — 24 HP iyileşir." },
      { name: "Map Monitor", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.4, duration: 3 },
        description: "Harita gözcülüğü — 3 tur defans %40 artar." }
    ]
  },
  {
    id: "wirerender",
    name: "Wirerender",
    project: "FdF",
    milestone: 2,
    track: "legacy",
    role: "Wireframe scout",
    color: "#48cae4",
    hp: 98, power: 3, defense: 10, speed: 4,
    moves: [
      { name: "Isometric Projection", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        effect: { stat: "accuracy", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Izometrik açı — hasar + kendi isabeti %30 artar.", buffSelf: true },
      { name: "Bresenham Blitz", type: "damage", basePower: 30, accuracy: 85, target: "enemy",
        description: "Bresenham çizgi taraması — yüksek hasar." },
      { name: "Color Gradient", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "power", modifier: 1.3, duration: 3 },
        description: "Renk gradient buff — 3 tur güç %30 artar." },
      { name: "Splitter String", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "ft_split kesiği — düşman gücü %20 düşer." },
      { name: "Loop Hook", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        description: "Hook döngüsü — kararlı vuruş." }
    ]
  },
  {
    id: "fractalus",
    name: "Fractalus",
    project: "fract-ol",
    spriteFile: "fract-ol.png",
    milestone: 2,
    track: "legacy",
    role: "Fractal mage",
    color: "#9b5de5",
    hp: 92, power: 4, defense: 9, speed: 4,
    moves: [
      { name: "Mandelbrot Madness", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 12, duration: 3 },
        description: "Mandelbrot çekirdeği — 3 tur tur başı 12 hasar." },
      { name: "Julia Judgment", type: "damage", basePower: 26, accuracy: 90, target: "enemy",
        description: "Julia kümesi — keskin yargı." },
      { name: "Iteration Infinity", type: "damage", basePower: 35, accuracy: 80, target: "enemy",
        description: "Sonsuz iterasyon — yüksek hasar, az isabet." },
      { name: "Zoom Vortex", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "accuracy", modifier: 1.3, duration: 3 },
        description: "Zoom girdabı — 3 tur isabet %30 artar." },
      { name: "Complex Crush", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "speed", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Karmaşık sayı çarpması — düşman hızı %20 düşer." }
    ]
  },
  {
    id: "shellshocker",
    name: "Shellshocker",
    project: "minishell",
    milestone: 3,
    track: "legacy",
    role: "Shell disruptor",
    color: "#f4a261",
    hp: 106, power: 4, defense: 10, speed: 4,
    moves: [
      { name: "Lexer Laser", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Lexer ışını — düşman isabeti %20 düşer." },
      { name: "Env Expansion", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "power", modifier: 1.4, duration: 3 },
        description: "Env genişletme — 3 tur güç %40 artar." },
      { name: "Fork Frenzy", type: "recoil", basePower: 30, accuracy: 88, target: "enemy",
        description: "Fork bombası — yüksek hasar, %25 geri tepme." },
      { name: "Pipe Punch", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Pipe geçişi — hasar + kendi hızı %30 artar.", buffSelf: true },
      { name: "Signal Silence", type: "stun", accuracy: 55, target: "enemy",
        effect: { duration: 1 },
        description: "Ctrl+C bastırır — 1 tur sersemleme." }
    ]
  },
  {
    id: "philonosopher",
    name: "Philonosopher",
    project: "philosophers",
    milestone: 3,
    track: "legacy",
    role: "Thread tactician",
    color: "#e76f51",
    hp: 112, power: 3, defense: 11, speed: 4,
    moves: [
      { name: "Thread Thump", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Thread vuruşu — hasar + kendi hızı %30 artar.", buffSelf: true },
      { name: "Mutex Mutate", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.5, duration: 3 },
        description: "Mutex kilidi — 3 tur defans %50 artar." },
      { name: "Deadlock Dismiss", type: "stun", accuracy: 70, target: "enemy",
        effect: { duration: 1 },
        description: "Deadlock tetikler — düşman 1 tur sırasını atlar." },
      { name: "Usleep Utility", type: "heal", basePower: 24, accuracy: 100, target: "self",
        description: "Tampon usleep — 24 HP iyileşir." },
      { name: "Data Race Detonator", type: "recoil", basePower: 55, accuracy: 85, target: "enemy",
        description: "Data race patlaması — devasa hasar, %25 geri tepme." }
    ]
  },
  {
    id: "raytracer",
    name: "Raytracer",
    project: "miniRT",
    milestone: 4,
    track: "legacy",
    role: "Ray mage",
    color: "#f72585",
    hp: 96, power: 4, defense: 9, speed: 4,
    moves: [
      { name: "Ray Intersection", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        description: "Işın kesişimi — kararlı hasar." },
      { name: "Vector Dot Product", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "accuracy", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Dot product — hasar + kendi isabeti %30 artar.", buffSelf: true },
      { name: "Phong Reflection", type: "damage", basePower: 30, accuracy: 85, target: "enemy",
        description: "Phong parlaması — yüksek hasar." },
      { name: "Normal Vector", type: "heal", basePower: 24, accuracy: 100, target: "self",
        description: "Normal vektör onarımı — 24 HP iyileşir." },
      { name: "Shadow Ray", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Gölge ışını — düşman isabeti %25 düşer." }
    ]
  },
  {
    id: "raycaster",
    name: "Raycaster",
    project: "cub3D",
    milestone: 4,
    track: "legacy",
    role: "Wall caster",
    color: "#fb8500",
    hp: 100, power: 4, defense: 10, speed: 4,
    moves: [
      { name: "DDA Dash", type: "damage", basePower: 30, accuracy: 88, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "DDA algoritması — hasar + kendi hızı %30 artar.", buffSelf: true },
      { name: "Fish-eye Fix", type: "heal", basePower: 22, accuracy: 100, target: "self",
        description: "Fish-eye düzeltme — 22 HP iyileşir." },
      { name: "Wall Texture", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.4, duration: 3 },
        description: "Duvar dokusu — 3 tur defans %40 artar." },
      { name: "FOV Flare", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "FOV alev — düşman isabeti %20 düşer." },
      { name: "Sprite Slice", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Sprite dilimi — düşman defansı %20 düşer." }
    ]
  },
  {
    id: "netweaver",
    name: "NetWeaver",
    project: "NetPractice",
    milestone: 4,
    track: "legacy",
    role: "Subnet weaver",
    color: "#00bbf9",
    hp: 104, power: 3, defense: 11, speed: 4,
    moves: [
      { name: "Subnet Slash (CIDR)", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        description: "CIDR taraması — kararlı hasar." },
      { name: "AND Operation", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Bitwise AND — düşman defansı %25 düşer." },
      { name: "Next Hop Hack", type: "damage", basePower: 32, accuracy: 82, target: "enemy",
        description: "Sonraki hop — yüksek hasar." },
      { name: "Broadcast Blast", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 10, duration: 3 },
        description: "Broadcast spam — 3 tur tur başı 10 hasar." },
      { name: "Gateway Guardian", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.5, duration: 3 },
        description: "Gateway koruması — 3 tur defans %50 artar." }
    ]
  },
  {
    id: "polymorphon",
    name: "Polymorphon",
    project: "C++ Modules 00-04",
    milestone: 4,
    track: "legacy",
    role: "OOP shapeshifter",
    color: "#c77dff",
    hp: 102, power: 4, defense: 11, speed: 4,
    moves: [
      { name: "Canonical Clamp", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "defense", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "Canonical form — hasar + kendi defansı %30 artar.", buffSelf: true },
      { name: "Virtual Vortex", type: "damage", basePower: 30, accuracy: 85, target: "enemy",
        description: "Virtual fonksiyon girdabı — yüksek hasar." },
      { name: "Stream Surge", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "speed", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "<< operatör akımı — düşman hızı %20 düşer." },
      { name: "Memory Mender", type: "heal", basePower: 28, accuracy: 100, target: "self",
        description: "Destructor tamiri — 28 HP iyileşir." },
      { name: "Abstract Arrow", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 1.2, duration: 2, chance: 1.0 },
        description: "Soyut sınıf oku — hasar + kendi gücü %20 artar.", buffSelf: true }
    ]
  },
  {
    id: "webcraft",
    name: "Webcraft",
    project: "webserv",
    milestone: 5,
    track: "legacy",
    role: "HTTP controller",
    color: "#ffb703",
    hp: 108, power: 4, defense: 11, speed: 4,
    moves: [
      { name: "Multiplexing Matrix", type: "damage", basePower: 30, accuracy: 88, target: "enemy",
        effect: { stat: "speed", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "epoll matrisi — hasar + kendi hızı %30 artar.", buffSelf: true },
      { name: "Socket Siege", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        description: "Socket kuşatması." },
      { name: "Status Shock", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.75, duration: 3, chance: 1.0 },
        description: "Status code şoku — düşman isabeti %25 düşer." },
      { name: "CGI Catalyst", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "power", modifier: 1.4, duration: 3 },
        description: "CGI scripti — 3 tur güç %40 artar." },
      { name: "Chunked Crush", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 10, duration: 3 },
        description: "Chunked transfer — 3 tur tur başı 10 hasar." }
    ]
  },
  {
    id: "irchon",
    name: "IRChon",
    project: "ft_irc",
    milestone: 5,
    track: "legacy",
    role: "IRC controller",
    color: "#90be6d",
    hp: 106, power: 4, defense: 11, speed: 4,
    moves: [
      { name: "Multiplexing Pulse (poll)", type: "damage", basePower: 30, accuracy: 88, target: "enemy",
        description: "poll() darbesi — yüksek hasar." },
      { name: "Authentication Arch", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.4, duration: 3 },
        description: "PASS kalkanı — 3 tur defans %40 artar." },
      { name: "Privilege Purge (KICK)", type: "stun", accuracy: 65, target: "enemy",
        effect: { duration: 1 },
        description: "KICK komutu — düşman 1 tur sersemler." },
      { name: "Private Whisper (PRIVMSG)", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "power", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "Gizli mesaj — düşman gücü %20 düşer." },
      { name: "Mode Manipulation", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "defense", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "MODE değişimi — düşman defansı %20 düşer." }
    ]
  },
  {
    id: "inceptord",
    name: "Inceptord",
    project: "Inception",
    milestone: 5,
    track: "legacy",
    role: "DevOps guardian",
    color: "#70e000",
    hp: 134, power: 3, defense: 13, speed: 3,
    moves: [
      { name: "Compose Command", type: "buff", accuracy: 100, target: "self",
        effect: { stat: "defense", modifier: 1.6, duration: 3 },
        description: "docker-compose up — 3 tur defans %60 artar." },
      { name: "Volume Vault", type: "heal", basePower: 30, accuracy: 100, target: "self",
        description: "Persistent volume — 30 HP iyileşir." },
      { name: "TLS Tether (Port 443)", type: "damage", basePower: 18, accuracy: 95, target: "enemy",
        effect: { stat: "accuracy", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "TLS handshake — düşman isabeti %20 düşer." },
      { name: "Build Bastion", type: "damage", basePower: 24, accuracy: 92, target: "enemy",
        effect: { stat: "power", modifier: 1.2, duration: 2, chance: 1.0 },
        description: "Dockerfile build — hasar + kendi gücü %20 artar.", buffSelf: true },
      { name: "Network Node", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 12, duration: 3 },
        description: "Container ağı — 3 tur tur başı 12 hasar." }
    ]
  },
  {
    id: "templatord",
    name: "Templatord",
    project: "C++ Modules 05-09",
    milestone: 5,
    track: "legacy",
    role: "STL apex mage",
    color: "#b5179e",
    hp: 100, power: 5, defense: 9, speed: 4,
    moves: [
      { name: "Exception Execute (Try-Catch)", type: "damage", basePower: 22, accuracy: 92, target: "enemy",
        effect: { stat: "defense", modifier: 1.3, duration: 2, chance: 1.0 },
        description: "try/catch zırhı — hasar + kendi defansı %30 artar.", buffSelf: true },
      { name: "Dynamic Cast Detonator", type: "recoil", basePower: 38, accuracy: 85, target: "enemy",
        description: "dynamic_cast patlaması — büyük hasar, %25 geri tepme." },
      { name: "Template Torrent", type: "damage", basePower: 28, accuracy: 88, target: "enemy",
        description: "Template instantiation seli — yüksek hasar." },
      { name: "Container Crush (STL)", type: "damage", basePower: 20, accuracy: 95, target: "enemy",
        effect: { stat: "defense", modifier: 0.8, duration: 3, chance: 1.0 },
        description: "STL container ezimi — düşman defansı %20 düşer." },
      { name: "RPN Reckoning (Module 09)", type: "dot", accuracy: 90, target: "enemy",
        effect: { modifier: 14, duration: 3 },
        description: "RPN hesaplayıcı — 3 tur tur başı 14 hasar." }
    ]
  }
];
